I can write words.

# This is a header
## this is a subheader

I can also make a list:
 * this is my first bullet
 * this is my second
 
This is a new line.

But to run this cell, I can press SHIFT+RETURN

Just in case I forget, ESC+m makes this cell a markdown, not programming cell.

SHIFT+RETURN to run like normal

In [3]:
print('Hi there CSCI-P14110!')

Hi there CSCI-P14110!


In [4]:
# this is a comment

In [6]:
# this is a comment

In [7]:
# I am going to print something
print('I am printing another thing here.')

I am printing another thing here.


## Data types and expressions
We need to understand a bit about the different types of data and objects in programming.

In [9]:
print(1) # print the number 1 -- here I have printed an integer, a whole number

1


In [10]:
print(1.5) # a number with a decimal point -- float

1.5


In [11]:
print('I am a string!') # printing out a string object

I am a string!


In [12]:
type(1) # looking at the type of number 1

int

In [13]:
type(1.5) # looking at the type of 1.5

float

In [14]:
type('I am a string!')

str

We can use Python like a calculator:

In [15]:
6+7

13

In [16]:
5.7*2

11.4

In [17]:
32/8

4.0

In [18]:
32/5

6.4

In [24]:
32//5

6

## Variables and assigning variables

In [19]:
thing = 1 # variable named "thing", I've given "thing" the value of 1

In [20]:
# use this variable in my program
print(thing)

1


In [21]:
type(thing)

int

In [22]:
thing2 = 'I am a string thing!'

In [23]:
print(thing2)

I am a string thing!


In [25]:
myString = '2'
type(myString)

str

In [27]:
type(int(myString))

int

A few more things about strings:

In [28]:
myString = 'I am a super cool string!'

In [29]:
print(myString)

I am a super cool string!


In [30]:
# pull out the 1st element of my string
print(myString[0]) # Python indexes starting at zero

I


In [32]:
print(myString[2])

a


In [33]:
myString[2]

'a'

In [34]:
# slice this string from its 1st to 4th index
myString[0:5] # I'm slicing from 0-index up to but NOT INCLUDING the 5th index -- stop at 4th index

'I am '

In [35]:
# also figure out how many elements are in the string object:
len(myString)

25

In [41]:
myUpperString = myString.upper() # object orient programming

In [37]:
print('Hi')

Hi


In [38]:
print("Hi")

Hi


In [39]:
print(" Hi ' ")

 Hi ' 


In [42]:
myUpperString

'I AM A SUPER COOL STRING!'

In [43]:
myString

'I am a super cool string!'

## Lists

In [44]:
myList = [1, 2, 3, 4, 5]

In [45]:
myList

[1, 2, 3, 4, 5]

In [46]:
myList[0]

1

In [47]:
myList[0:3]

[1, 2, 3]

In [48]:
# a few other a (little weird) ways to slice things

# slice starting from a element and then all the way to the end
myList[2:]

[3, 4, 5]

In [50]:
myList[:-2] # slicing all the way until then 2nd to last element

[1, 2, 3]

In [51]:
# lists of "mixed" variable types
mySecondList = [1, 3.5, 'hi there']

In [52]:
mySecondList

[1, 3.5, 'hi there']

In [53]:
# I'll add another element to this list
mySecondList.append('another element')

In [54]:
mySecondList

[1, 3.5, 'hi there', 'another element']

## Numpy arrays (NumPy)

In [55]:
myList = [1, 2, 3]

In [56]:
myList

[1, 2, 3]

In [57]:
myList[0] = myList[0] + 5

In [58]:
myList

[6, 2, 3]

In [59]:
myList+5

TypeError: can only concatenate list (not "int") to list

In [60]:
import numpy

In [61]:
#!conda install -c anaconda numpy --yes

In [62]:
print(numpy)

<module 'numpy' from '/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'>


In [63]:
myArray = numpy.array([4.4, 6.7, 7.0])

In [64]:
myArray

array([4.4, 6.7, 7. ])

In [65]:
# now I can add the value of 5 to all the elements of this list:
myArray = myArray + 5

In [66]:
myArray

array([ 9.4, 11.7, 12. ])

In [67]:
myArray2 = numpy.array([5,6,7])

In [68]:
myArray2

array([5, 6, 7])

In [69]:
# I'm going to import NumPy with a shorthand
import numpy as np

In [70]:
myArray3 = np.array([6,7,8])

In [71]:
myArray3

array([6, 7, 8])

First thing I'm going to do is let the students know that I get that its weird right now and make sure that I'm listening to what they need.  Another thing I'm going to do is make sure all of the class materials are accessible for all internet connections. If I eat a lot of chocolate over the next 2 weeks that is fine!