# An intro to Python & Jupyter notebooks

This is a jupyter notebook!  It is actually running in your browser and translating it into Python!  Super neat.  It allows us to write text AND code in the same place.  For example, this is a markdown cell where I can write myself notes.

First we'll take a tour of jupyter notebooks:
* run a cell:

In [1]:
print('Hi there')

Hi there


A few ways to run a cell:
* with the ">" button
* with Cell -> Run Cells
* my fav: SHIFT+RET

Note: colors automatically change in jupyter notebook -- jupyter notebook is trying to help you with helpful coloring!

A tour of markdown:

* Headers with "#"
* Lists
* *italics* and **bold**

Go into Markdown with Cell -> Cell Type -> Markdown or my fav: ESC+m

## Comments

Sometimes we want to leave ourselves (or others!) some notes in our code, we can do this with the `#` symbols:

In [2]:
# this bit of code doesn't get run

## Data types and expressions

In [3]:
print(1) # integers -- look another comment!

1


In [4]:
print(1.5) # float

1.5


In [5]:
print('Hello there!') # a string

Hello there!


We can figure out what "type" of object we are dealing with by using the `type` function (more on functions in the next few days):

In [6]:
type(1)

int

In [7]:
type(1.5)

float

In [8]:
type('Hello there!')

str

The last one "str" means string.

We can use Python like a big fancy calculator too:

In [9]:
5+6

11

In [10]:
5.5+6

11.5

In [11]:
32/8

4.0

Note: in the above one even though we used two integers we got out a floating number -- this is because Python automatically converts integers to floats on division so that it won't give you the wrong answer on something like:

In [12]:
32/5

6.4

## Variables and assignments

In [13]:

# single assignment

thing = 1

# so thing is my variable name, and 1 is the value.  
# thing is now associated with the value of 1
# when I print out 1 and thing, they would appear the same
# the object type is also going to be the same, 
# because the variable inherets what the contents are

print(1)
print(thing)

print( type(1) )
print( type(thing) )

1
1
<class 'int'>
<class 'int'>


In [14]:
# multiple assignment

# You won't use this too often, but you'll see it when we start
# working with more complex data structures
# copy this code into PyCharm and play around with it a bit to explore

x = 'fizzy'
y = 'pop'

a, b = x, y

print(x, y)
print(a, b)

fizzy pop
fizzy pop


## More on strings

String variables come with some interesting things we can do with them:

In [15]:
myText = 'I am some text, pretty neat!'

In [16]:
print(myText)

I am some text, pretty neat!


We can grab individual letters by their *index*:

In [17]:
print(myText[1]) # here I'm grabbing the letter at index 1 by using "[1]"

In [18]:
print(myText[0])

I


Note I got a space when I grabbed the index 1, but actually got the first element for an index of 0.

This is because Python "indexes starting at zero".  Other codes start at 1, but Python starts at 0.

We can grab parts of string by "slicing":

In [19]:
print(myText[0:5])

I am 


How long is our string?

In [20]:
print(len(myText))

28


Using the "len" function tells us that our bit of text is 28 characters long.

Depending on the type of variable we are using there are sometimes functions that are "associated" with each variable that can be accessed with a "."

For example, if we have a string variable, we can make it all upper case with:

In [21]:
print(myText.upper())

I AM SOME TEXT, PRETTY NEAT!


We won't be using too many of these, but if you've ever heard of "object oriented programming" this is what is being refered to -- this function `upper()` is *associated* with the *object* `myText`.

Some other Python-specific things, both ' and " are fine:

In [22]:
print('Hi!')

Hi!


In [23]:
print("Hi!")

Hi!


You can also combine them in weird ways:

In [24]:
print(" ' ")

 ' 


In [26]:
print('"')

"


Also, we can do big bunches of text with three ":

In [27]:
largeText = """

So much text!

I have so many things to say.

I can't think of them right now, but I'm sure they are there in my brain.

"""

In [28]:
print(largeText)



So much text!

I have so many things to say.

I can't think of them right now, but I'm sure they are there in my brain.




## Lists

Another useful type of variable is the list type.

In [31]:
myList = [1, 2, 3, 4, 5]

In [32]:
print(myList)

[1, 2, 3, 4, 5]


We can index lists a lot like strings:

In [33]:
print(myList[0])

1


and slice as well:

In [34]:
print(myList[0:3])

[1, 2, 3]


What do you think the following does?

```python
print(myList[2:])
```

Or what about:

```python
print(myList[:-2])
```

Lists are a little weird because you can "mix" different types of things:

In [35]:
mySecondList = [1, 3, 5.5, 'hi there']

In [36]:
print(mySecondList)

[1, 3, 5.5, 'hi there']


Lists also have some "special" functions, like let's say we want to add another element to our list -- we do this with the `append` function that *belongs* to whatever list we are dealing with:

In [37]:
mySecondList.append('another element!')

In [38]:
print(mySecondList)

[1, 3, 5.5, 'hi there', 'another element!']


## Numpy arrays

One thing that we might want to do is do math to an element of a list:

In [39]:
myList = [1, 2, 3]

In [40]:
myList[0] = myList[0] + 5

In [41]:
print(myList)

[6, 2, 3]


Naturally, an extention of this would be to add 5 to *all* elements of the list, let's see what happens when we try to do this:

In [42]:
myList = myList + 5

TypeError: can only concatenate list (not "int") to list

Whoa -- what happened??  This has to do with the type of object that the list is in Python.  (If you go into CS you'll learn more about this).  For our purposes we can get around this by using a set of functions from the `numpy` library.

To use these functions we have to load in this library since it doesn't come "pre-packaged" with Python:

In [43]:
import numpy

Did you get an error?  Try:

In [45]:
#!conda install -c anaconda numpy ---yes

This *installs* the package with Anaconda.  You can also do this with the GUI!

In [44]:
print(numpy)

<module 'numpy' from '/Users/jillnaiman/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'>


Ok, so that might be a little funny looking, but this is basically telling us that all the code for the `numpy` library is stored in site-packages.

Let's make an array with numpy:

In [47]:
myArray = numpy.array([4.1, 4.4, 3.5])

In [48]:
print(myArray)

[4.1 4.4 3.5]


We can then do stuff we want to!

In [49]:
myArray = myArray + 5

In [50]:
print(myArray)

[9.1 9.4 8.5]


You can also import packages with a "shorthand".  The one you see most with numpy is np:

In [51]:
import numpy as np

... then we can do:

In [52]:
myArray = np.array([5, 6, 7.7])

In [53]:
print(myArray)

[5.  6.  7.7]
