# EXTRA STUFF: Day 8

First, import our usual things:

In [1]:
import ipywidgets
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import bqplot.pyplot as bplt
# also:
import bqplot

Load data:

In [8]:
planets = pd.read_csv('https://jnaiman.github.io/csci-p-14110_su2020/lesson08/planets_2020.06.22_10.10.17.csv', 
                     sep=",", comment="#")

Let's take a quick look:

In [9]:
planets

rowid pl_hostname pl_letter     pl_name    pl_discmethod  \
0         1      11 Com         b    11 Com b  Radial Velocity   
1         2      11 UMi         b    11 UMi b  Radial Velocity   
2         3      14 And         b    14 And b  Radial Velocity   
3         4      14 Her         b    14 Her b  Radial Velocity   
4         5    16 Cyg B         b  16 Cyg B b  Radial Velocity   
...     ...         ...       ...         ...              ...   
4159   4160     tau Gem         b   tau Gem b  Radial Velocity   
4160   4161     ups And         b   ups And b  Radial Velocity   
4161   4162     ups And         c   ups And c  Radial Velocity   
4162   4163     ups And         d   ups And d  Radial Velocity   
4163   4164      xi Aql         b    xi Aql b  Radial Velocity   

      pl_controvflag  pl_pnum    pl_orbper  pl_orbpererr1  pl_orbpererr2  ...  \
0                  0        1   326.030000       0.320000      -0.320000  ...   
1                  0        1   516.219970       3.200000      -3.200000  ...   
2                  0        1   185.840000       0.230000      -0.230000  ...   
3                  0        1  1773.400020       2.500000      -2.500000  ...   
4                  0        1   798.500000       1.000000      -1.000000  ...   
...              ...      ...          ...            ...            ...  ...   
4159               0        1   305.500000       0.100000      -0.100000  ...   
4160               0        3     4.617033       0.000023      -0.000023  ...   
4161               0        3   241.258000       0.064000      -0.064000  ...   
4162               0        3  1276.460000       0.570000      -0.570000  ...   
4163               0        1   136.750000       0.250000      -0.250000  ...   

      st_bmy  st_bmyerr  st_bmylim  st_m1  st_m1err  st_m1lim  st_c1  \
0        NaN        NaN        NaN    NaN       NaN       NaN    NaN   
1        NaN        NaN        NaN    NaN       NaN       NaN    NaN   
2        NaN        NaN        NaN    NaN       NaN       NaN    NaN   
3      0.537      0.001        0.0  0.366     0.002       0.0  0.438   
4      0.418      0.003        0.0  0.222     0.003       0.0  0.351   
...      ...        ...        ...    ...       ...       ...    ...   
4159     NaN        NaN        NaN    NaN       NaN       NaN    NaN   
4160     NaN        NaN        NaN    NaN       NaN       NaN    NaN   
4161     NaN        NaN        NaN    NaN       NaN       NaN    NaN   
4162     NaN        NaN        NaN    NaN       NaN       NaN    NaN   
4163     NaN        NaN        NaN    NaN       NaN       NaN    NaN   

      st_c1err  st_c1lim  st_colorn  
0          NaN       NaN        7.0  
1          NaN       NaN        5.0  
2          NaN       NaN        7.0  
3        0.006       0.0        9.0  
4        0.003       0.0       17.0  
...        ...       ...        ...  
4159       NaN       NaN        7.0  
4160       NaN       NaN        8.0  
4161       NaN       NaN        8.0  
4162       NaN       NaN        8.0  
4163       NaN       NaN        9.0  

[4164 rows x 356 columns]

## Heatmap dashboard

Let's make a 2D histogram showing how the NASA planets are distributed across these 2 parameters.

First, looking at the plots of the individual distributions, we can make some guesses for bins along each parameter:

In [10]:
ecc = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]

We can also do this with NumPy:

In [11]:
ecc = np.arange(0.0, 1.1, step=0.1) # start, stop, step => note step+stop there!

In [12]:
ecc

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

And semi-major axis:

In [13]:
sa = np.arange(0.0, 50+5, step=5)

In [14]:
sa

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

Let's also use NumPy to make a 2D histogram with these bins:

In [15]:
myHist, xedges, yedges = np.histogram2d(planets['pl_orbeccen'], planets['pl_orbsmax'], 
                                        bins=[ecc,sa])

In [16]:
yedges

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [17]:
myHist

array([[596.,  14.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [261.,   6.,   1.,   1.,   0.,   0.,   0.,   0.,   0.,   0.],
       [158.,   6.,   2.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ 80.,   5.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ 49.,   2.,   2.,   1.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ 43.,   4.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ 20.,   2.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ 15.,   4.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.],
       [  9.,   2.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  3.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]])

We see that we mostly have entries between 0-25 AU, so we can update our binning:

In [18]:
sa = np.arange(0.0, 24+4, step=4)

In [19]:
myHist, xedges, yedges = np.histogram2d(planets['pl_orbeccen'], planets['pl_orbsmax'], 
                                        bins=[ecc,sa])

In [20]:
yedges

array([ 0.,  4.,  8., 12., 16., 20., 24.])

In [21]:
myHist

array([[592.,  16.,   2.,   0.,   0.,   0.],
       [257.,  10.,   1.,   0.,   1.,   0.],
       [154.,   8.,   4.,   0.,   0.,   0.],
       [ 78.,   6.,   1.,   1.,   0.,   0.],
       [ 46.,   4.,   2.,   1.,   1.,   0.],
       [ 38.,   9.,   0.,   0.,   0.,   0.],
       [ 17.,   5.,   0.,   0.,   0.,   0.],
       [ 14.,   5.,   0.,   0.,   0.,   1.],
       [  9.,   2.,   0.,   0.,   1.,   0.],
       [  3.,   0.,   0.,   0.,   0.,   0.]])

xedges & yedges give the bin *edges* but we want the centers:

In [22]:
xcenter = (xedges[:-1] + xedges[1:]) / 2
ycenter = (yedges[:-1] + yedges[1:]) / 2

In [23]:
myLabel = ipywidgets.Label()# make label

Function to print out data values:

In [24]:
def get_data_value(change): # redefine this function to now use myHist, not data
    i,j = change['owner'].selected[0]
    v = myHist[i,j] # grab data value
    myLabel.value = 'Value of data = ' + str(v) 

Put all together:

In [25]:
fig = bplt.figure(padding_y=0.0) # set up a figure object

# use bqplot's plt interface to plot:
heat_map = bplt.gridheatmap(myHist, row=xcenter, column=ycenter, interactions={'click':'select'})

# hook heat_maps selected value to the label 
heat_map.observe(get_data_value, 'selected')

# show both the fig and label in a vertical box
ipywidgets.VBox([myLabel,fig])

We can change the color scale as well:

In [26]:
fig = bplt.figure(padding_y=0.0) # set up a figure object

# add in color:
col_sc = bqplot.ColorScale(scheme='Reds') 

# use bqplot's plt interface to plot:
heat_map = bplt.gridheatmap(myHist, row=xcenter, column=ycenter, interactions={'click':'select'},
                          scales={'color':col_sc})

# hook heat_maps selected value to the label 
heat_map.observe(get_data_value, 'selected')

# show both the fig and label in a vertical box
ipywidgets.VBox([myLabel,fig])

However, doing things like adding in x/y labels is somewhat familiar, but we call fig.axes instead of ax[#] to set axis labels.  You can check out what fig.axes[0], fig.axes[1], fig.axes[2] is by:

In [27]:
fig.axes

[ColorAxis(scale=ColorScale(scheme='Reds')),
 Axis(scale=LinearScale(), side='bottom'),
 Axis(orientation='vertical', scale=LinearScale(), side='left')]

So, it looks like the 0th axes is color, the 1th one is the horizontal axis and the 2th is the vertical axes.  We can change x/y labels as follows:

In [28]:
fig = bplt.figure(padding_y=0.0) # set up a figure object
bplt.scales(scales={'color':bqplot.ColorScale(scheme='Reds')})

# use bqplot's plt interface to plot:
heat_map = bplt.gridheatmap(myHist, row=xcenter, column=ycenter, interactions={'click':'select'})

# hook heat_maps selected value to the label 
heat_map.observe(get_data_value, 'selected')

# change labels
fig.axes[0].side = 'top' # so it doesn't overlap with scale
fig.axes[1].label = 'semi-major axes in AU' # xaxes label
fig.axes[2].label = 'eccentricity' # yaxes label

# show both the fig and label in a vertical box
ipywidgets.VBox([myLabel,fig])

Now let's generate our line plot -- this will use the $r(\theta)$ equation to plot orbits:

In [29]:
fig_lines = bplt.figure(padding_y=0.0) # set up a figure object

# use bqplot's plt interface to plot:
lines = bplt.plot([],[]) # empty to start

# change labels
fig_lines.axes[0].label = 'x in AU' # xaxes label
fig_lines.axes[1].label = 'y in AU' # yaxes label

fig_lines # empty plot of x/y

Figure(axes=[Axis(label='x in AU', scale=LinearScale()), Axis(label='y in AU', orientation='vertical', scale=L…

Now, lets first put all of our plots in the alighment we want, keeping in mind that the x/y plot of the analytical trajectory won't be updated when we click anything yet:

In [30]:
ipywidgets.VBox([myLabel,ipywidgets.HBox([fig,fig_lines])])

Oh but it looks squished, lets try messing with the layout:

In [31]:
fig.layout.min_width='500px'
fig_lines.layout.min_width='500px'
ipywidgets.VBox([myLabel,ipywidgets.HBox([fig,fig_lines])])

#figOut = ipywidgets.VBox([myLabel,ipywidgets.HBox([fig,fig_lines])])
#figOut.layout.min_width='1000px'
#figOut

To make this interactive first we need to update our `get_data_value` function to *also* update our lines plot when the heatmap plot is selected:

In [32]:
theta = np.arange(0, 2*np.pi, 0.001) # theta array

def get_data_value(change): # redefine this function to now use myHist, not data
    # 1. Update the label
    i,j = change['owner'].selected[0]
    v = myHist[i,j] # grab data value
    myLabel.value = 'Value of data = ' + str(v) 
    # 2. Update the x/y values in our lines plot
    a = ycenter[j] # semi major axis based on bins in heatmap
    ecc = xcenter[i] # eccentricity for bins on heatmap
    r = a*(1-ecc**2)/(1+ecc*np.cos(theta)) # calculate r(theta)
    x = r*np.cos(theta) # translate into x/y
    y = r*np.sin(theta)
    lines.x = x
    lines.y = y

Finally before we plot, we have to re-hook this back into our heatmap figure:

In [33]:
heat_map.observe(get_data_value, 'selected')

Now use the orientation of our plots we had above to re-plot with new interactivity:

In [34]:
ipywidgets.VBox([myLabel,ipywidgets.HBox([fig,fig_lines])])

If we want to keep the x/y range static when we plot, we can re-do our trajectory plot with:

In [35]:
fig_lines = bplt.figure(padding_y=0.0) # set up a figure object

# use bqplot's plt interface to plot:
lines = bplt.plot([],[]) # empty to start

# set x/y lim in the bqplot way
bplt.set_lim(-30,30,'x')
bplt.set_lim(-30,30, 'y')

# change labels
fig_lines.axes[0].label = 'x in AU' # xaxes label
fig_lines.axes[1].label = 'y in AU' # yaxes label

# to be sure:
fig_lines.layout.min_width='500px'


fig_lines # empty plot of x/y

Figure(axes=[Axis(label='x in AU', scale=LinearScale(max=30.0, min=-30.0)), Axis(label='y in AU', orientation=…

And finally put it all together:

In [36]:
ipywidgets.VBox([myLabel,ipywidgets.HBox([fig,fig_lines])])