# EXTRA STUFF: Day 8

First, import our usual things:

In [23]:
import ipywidgets
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import bqplot.pyplot as bplt
# also:
import bqplot

Load data:

In [2]:
planets = pd.read_csv('https://jnaiman.github.io/csci-p-14110_su2020/lesson08/planets_2020.06.17_14.04.11.csv', 
                     sep=",", comment="#")

Let's take a quick look:

In [3]:
planets

loc_rowid pl_hostname pl_letter     pl_name    pl_discmethod  \
0             1      11 Com         b    11 Com b  Radial Velocity   
1             2      11 UMi         b    11 UMi b  Radial Velocity   
2             3      14 And         b    14 And b  Radial Velocity   
3             4      14 Her         b    14 Her b  Radial Velocity   
4             5    16 Cyg B         b  16 Cyg B b  Radial Velocity   
...         ...         ...       ...         ...              ...   
4159       4160     tau Gem         b   tau Gem b  Radial Velocity   
4160       4161     ups And         b   ups And b  Radial Velocity   
4161       4162     ups And         c   ups And c  Radial Velocity   
4162       4163     ups And         d   ups And d  Radial Velocity   
4163       4164      xi Aql         b    xi Aql b  Radial Velocity   

      pl_controvflag  pl_pnum    pl_orbper  pl_orbpererr1  pl_orbpererr2  ...  \
0                  0        1   326.030000       0.320000      -0.320000  ...   
1                  0        1   516.219970       3.200000      -3.200000  ...   
2                  0        1   185.840000       0.230000      -0.230000  ...   
3                  0        1  1773.400020       2.500000      -2.500000  ...   
4                  0        1   798.500000       1.000000      -1.000000  ...   
...              ...      ...          ...            ...            ...  ...   
4159               0        1   305.500000       0.100000      -0.100000  ...   
4160               0        3     4.617033       0.000023      -0.000023  ...   
4161               0        3   241.258000       0.064000      -0.064000  ...   
4162               0        3  1276.460000       0.570000      -0.570000  ...   
4163               0        1   136.750000       0.250000      -0.250000  ...   

      st_mass  st_masserr1  st_masserr2  st_masslim  st_rad  st_raderr1  \
0        2.70         0.30        -0.30         0.0   19.00        2.00   
1        2.78         0.69        -0.69         0.0   29.79        2.84   
2        2.20         0.10        -0.20         0.0   11.00        1.00   
3        0.90         0.04        -0.04         0.0    0.93        0.01   
4        1.08         0.04        -0.04         0.0    1.13        0.01   
...       ...          ...          ...         ...     ...         ...   
4159     2.30         0.30        -0.30         0.0   26.80        0.70   
4160     1.30          NaN          NaN         0.0    1.56         NaN   
4161     1.30          NaN          NaN         0.0    1.56         NaN   
4162     1.30          NaN          NaN         0.0    1.56         NaN   
4163     2.20          NaN          NaN         0.0   12.00         NaN   

      st_raderr2  st_radlim   rowupdate  \
0          -2.00        0.0  2014-05-14   
1          -2.84        0.0  2018-09-06   
2          -1.00        0.0  2014-05-14   
3          -0.01        0.0  2018-09-06   
4          -0.01        0.0  2018-09-06   
...          ...        ...         ...   
4159       -0.70        0.0  2014-05-14   
4160         NaN        0.0  2019-01-31   
4161         NaN        0.0  2019-01-31   
4162         NaN        0.0  2019-01-31   
4163         NaN        0.0  2014-05-14   

                                 pl_facility  
0                           Xinglong Station  
1     Thueringer Landessternwarte Tautenburg  
2          Okayama Astrophysical Observatory  
3                     W. M. Keck Observatory  
4                     Multiple Observatories  
...                                      ...  
4159                        Lick Observatory  
4160                        Lick Observatory  
4161                  Multiple Observatories  
4162                  Multiple Observatories  
4163       Okayama Astrophysical Observatory  

[4164 rows x 73 columns]

## Heatmap dashboard

Let's make a 2D histogram showing how the NASA planets are distributed across these 2 parameters.

First, looking at the plots of the individual distributions, we can make some guesses for bins along each parameter:

In [4]:
ecc = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]

We can also do this with NumPy:

In [5]:
ecc = np.arange(0.0, 1.1, step=0.1) # start, stop, step => note step+stop there!

In [6]:
ecc

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

And semi-major axis:

In [7]:
sa = np.arange(0.0, 50+5, step=5)

In [8]:
sa

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

Let's also use NumPy to make a 2D histogram with these bins:

In [9]:
myHist, xedges, yedges = np.histogram2d(planets['pl_orbeccen'], planets['pl_orbsmax'], 
                                        bins=[ecc,sa])

In [10]:
yedges

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [11]:
myHist

array([[596.,  14.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [261.,   6.,   1.,   1.,   0.,   0.,   0.,   0.,   0.,   0.],
       [158.,   6.,   2.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ 80.,   5.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ 49.,   2.,   2.,   1.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ 43.,   4.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ 20.,   2.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ 15.,   4.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.],
       [  9.,   2.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  3.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]])

We see that we mostly have entries between 0-25 AU, so we can update our binning:

In [12]:
sa = np.arange(0.0, 24+4, step=4)

In [13]:
myHist, xedges, yedges = np.histogram2d(planets['pl_orbeccen'], planets['pl_orbsmax'], 
                                        bins=[ecc,sa])

In [14]:
yedges

array([ 0.,  4.,  8., 12., 16., 20., 24.])

In [15]:
myHist

array([[592.,  16.,   2.,   0.,   0.,   0.],
       [257.,  10.,   1.,   0.,   1.,   0.],
       [154.,   8.,   4.,   0.,   0.,   0.],
       [ 78.,   6.,   1.,   1.,   0.,   0.],
       [ 46.,   4.,   2.,   1.,   1.,   0.],
       [ 38.,   9.,   0.,   0.,   0.,   0.],
       [ 17.,   5.,   0.,   0.,   0.,   0.],
       [ 14.,   5.,   0.,   0.,   0.,   1.],
       [  9.,   2.,   0.,   0.,   1.,   0.],
       [  3.,   0.,   0.,   0.,   0.,   0.]])

xedges & yedges give the bin *edges* but we want the centers:

In [16]:
xcenter = (xedges[:-1] + xedges[1:]) / 2
ycenter = (yedges[:-1] + yedges[1:]) / 2

In [17]:
myLabel = ipywidgets.Label()# make label

Function to print out data values:

In [18]:
def get_data_value(change): # redefine this function to now use myHist, not data
    i,j = change['owner'].selected[0]
    v = myHist[i,j] # grab data value
    myLabel.value = 'Value of data = ' + str(v) 

Put all together:

In [21]:
fig = bplt.figure(padding_y=0.0) # set up a figure object

# use bqplot's plt interface to plot:
heat_map = bplt.gridheatmap(myHist, row=xcenter, column=ycenter, interactions={'click':'select'})

# hook heat_maps selected value to the label 
heat_map.observe(get_data_value, 'selected')

# show both the fig and label in a vertical box
ipywidgets.VBox([myLabel,fig])

We can change the color scale as well:

In [43]:
fig = bplt.figure(padding_y=0.0) # set up a figure object

# add in color:
col_sc = bqplot.ColorScale(scheme='Reds') 

# use bqplot's plt interface to plot:
heat_map = bplt.gridheatmap(myHist, row=xcenter, column=ycenter, interactions={'click':'select'},
                          scales={'color':col_sc})

# hook heat_maps selected value to the label 
heat_map.observe(get_data_value, 'selected')

# show both the fig and label in a vertical box
ipywidgets.VBox([myLabel,fig])

However, doing things like adding in x/y labels is somewhat familiar, but we call fig.axes instead of ax[#] to set axis labels.  You can check out what fig.axes[0], fig.axes[1], fig.axes[2] is by:

In [44]:
fig.axes

[ColorAxis(scale=ColorScale(scheme='Reds')),
 Axis(scale=LinearScale(), side='bottom'),
 Axis(orientation='vertical', scale=LinearScale(), side='left')]

So, it looks like the 0th axes is color, the 1th one is the horizontal axis and the 2th is the vertical axes.  We can change x/y labels as follows:

In [45]:
fig = bplt.figure(padding_y=0.0) # set up a figure object
bplt.scales(scales={'color':bqplot.ColorScale(scheme='Reds')})

# use bqplot's plt interface to plot:
heat_map = bplt.gridheatmap(myHist, row=xcenter, column=ycenter, interactions={'click':'select'})

# hook heat_maps selected value to the label 
heat_map.observe(get_data_value, 'selected')

# change labels
fig.axes[0].side = 'top' # so it doesn't overlap with scale
fig.axes[1].label = 'semi-major axes in AU' # xaxes label
fig.axes[2].label = 'eccentricity' # yaxes label

# show both the fig and label in a vertical box
ipywidgets.VBox([myLabel,fig])

Now let's generate our line plot -- this will use the $r(\theta)$ equation to plot orbits:

In [46]:
fig_lines = bplt.figure(padding_y=0.0) # set up a figure object

# use bqplot's plt interface to plot:
lines = bplt.plot([],[]) # empty to start

# change labels
fig_lines.axes[0].label = 'x in AU' # xaxes label
fig_lines.axes[1].label = 'y in AU' # yaxes label

fig_lines # empty plot of x/y

Figure(axes=[Axis(label='x in AU', scale=LinearScale()), Axis(label='y in AU', orientation='vertical', scale=L…

Now, lets first put all of our plots in the alighment we want, keeping in mind that the x/y plot of the analytical trajectory won't be updated when we click anything yet:

In [47]:
ipywidgets.VBox([myLabel,ipywidgets.HBox([fig,fig_lines])])

Oh but it looks squished, lets try messing with the layout:

In [48]:
fig.layout.min_width='500px'
fig_lines.layout.min_width='500px'
ipywidgets.VBox([myLabel,ipywidgets.HBox([fig,fig_lines])])

#figOut = ipywidgets.VBox([myLabel,ipywidgets.HBox([fig,fig_lines])])
#figOut.layout.min_width='1000px'
#figOut

To make this interactive first we need to update our `get_data_value` function to *also* update our lines plot when the heatmap plot is selected:

In [49]:
theta = np.arange(0, 2*np.pi, 0.001) # theta array

def get_data_value(change): # redefine this function to now use myHist, not data
    # 1. Update the label
    i,j = change['owner'].selected[0]
    v = myHist[i,j] # grab data value
    myLabel.value = 'Value of data = ' + str(v) 
    # 2. Update the x/y values in our lines plot
    a = ycenter[j] # semi major axis based on bins in heatmap
    ecc = xcenter[i] # eccentricity for bins on heatmap
    r = a*(1-ecc**2)/(1+ecc*np.cos(theta)) # calculate r(theta)
    x = r*np.cos(theta) # translate into x/y
    y = r*np.sin(theta)
    lines.x = x
    lines.y = y

Finally before we plot, we have to re-hook this back into our heatmap figure:

In [50]:
heat_map.observe(get_data_value, 'selected')

Now use the orientation of our plots we had above to re-plot with new interactivity:

In [51]:
ipywidgets.VBox([myLabel,ipywidgets.HBox([fig,fig_lines])])

If we want to keep the x/y range static when we plot, we can re-do our trajectory plot with:

In [56]:
fig_lines = bplt.figure(padding_y=0.0) # set up a figure object

# use bqplot's plt interface to plot:
lines = bplt.plot([],[]) # empty to start

# set x/y lim in the bqplot way
bplt.set_lim(-30,30,'x')
bplt.set_lim(-30,30, 'y')

# change labels
fig_lines.axes[0].label = 'x in AU' # xaxes label
fig_lines.axes[1].label = 'y in AU' # yaxes label

# to be sure:
fig_lines.layout.min_width='500px'


fig_lines # empty plot of x/y

Figure(axes=[Axis(label='x in AU', scale=LinearScale(max=30.0, min=-30.0)), Axis(label='y in AU', orientation=…

And finally put it all together:

In [57]:
ipywidgets.VBox([myLabel,ipywidgets.HBox([fig,fig_lines])])